<script lang="ts">
</script>

<div class="flex w-sm flex-col items-center gap-3 lg:w-lg">
	<p>
		I'm a software developer, systems engineer, and astrophysicist located in the Bay Area, CA.
		After graduating from UC Berkeley, where I studied Astrophysics and Computer Science, I've been
		working at the Lawrence Berkeley National Laboratory, where I developed software and
		infrastructure for processing images generated by large-scale optical telescope surveys.
	</p>

	<p>
		I enjoy studying and mastering new topics in both computing and physics, and in my free time I
		read sci-fi, play tabletop games, and explore nature hikes in my area. I especially love to
		experiment with the intersection of web development and my other interests, and often create web
		applications to explore complex game systems in greater detail.
	</p>
</div>
