<script lang="ts">
	import { sharedWidths } from '$lib/scripts/sharedVariables.svelte';
</script>

<div class="flex flex-col items-center gap-2 {sharedWidths}">
	<h1>Hi, I'm William</h1>
	<p>
		I'm a software developer, systems engineer, and astrophysicist located in the Bay Area, CA.
		After graduating from UC Berkeley, where I studied Astrophysics and Computer Science, I've been
		working at the Lawrence Berkeley National Laboratory developing software and infrastructure for
		processing images generated by large-scale optical telescope surveys.
	</p>

	<p>
		I enjoy studying and mastering new topics in both computing and physics, and in my free time I
		read sci-fi, play tabletop games, and explore nature hikes in my area. I especially love to
		experiment with the intersection of web development and my other interests, and often create web
		applications to explore complex game systems in greater detail.
	</p>

	<p>
		I'm currently looking for work. Commutes or relocation is no issue, and I'm happy to hear from
		any interested parties.
	</p>
</div>
